/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function startListening() {
    return invoke()<null>("start_listening")
}

export function connect(address: string, port: number) {
    return invoke()<null>("connect", { address,port })
}

export function getClipboardHistory() {
    return invoke()<ClipboardData[]>("get_clipboard_history")
}

export type ClipboardData = { data_type: ClipboardType; data: string; datetime: string }
export type ClipboardType = "Text" | "Image" | "File"
