/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function startListening() {
    return invoke()<null>("start_listening")
}

export function connect(address: string, port: number) {
    return invoke()<null>("connect", { address,port })
}

export function getClipboardHistory() {
    return invoke()<ClipboardData[]>("get_clipboard_history")
}

export function deleteClipboardHistory(uuid: string) {
    return invoke()<null>("delete_clipboard_history", { uuid })
}

export function copyClipboardFrom(uuid: string) {
    return invoke()<null>("copy_clipboard_from", { uuid })
}

export type ClipboardType = "Text" | "Image" | "File"
export type ClipboardData = { uuid: string; data_type: ClipboardType; data: string; datetime: string }
